add solution for 05-lection3-template
js-tasks-ru/htmlcss-20221107_vadim07 pull request #13
Opened 2022-12-01 22:08 UTC by tsyk007

2022-12-01 22:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-02 08:10 UTC, GSemikozov requested changes

2022-12-02 08:10 UTC, GSemikozov commented on components/header/header.css
> +.header_inner {
лишнее - высота хедера должна определяться как раз паддингами и внутренним содержимым (сейчас это может быть лого). А вот что для внутренней страницы действительно надо - так это прозрачный фон

2022-12-02 12:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-02 12:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-12-06 07:12 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-12-06 07:12 UTC, GSemikozov approved these changes

2022-12-06 07:12 UTC, merged