add solution for 07-lection5 04-input
js-tasks-ru/htmlcss-20221107_vadim07 pull request #22
Opened 2022-12-11 16:52 UTC by tsyk007

2022-12-11 16:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-14 23:26 UTC, GSemikozov requested changes

2022-12-14 23:26 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <label class="input">
в случае с инпутом не надо заворачивать весь контент в label

2022-12-14 23:26 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <h5 class="input__label">label</h5>
это `label`

2022-12-14 23:26 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <span>
здесь должен быть класс

2022-12-14 23:26 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <span>
с position: relative

2022-12-15 16:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-15 16:29 UTC, GSemikozov approved these changes

2022-12-15 16:29 UTC, merged