add solution for dz03-lection1 01-button
js-tasks-ru/htmlcss-20221107_vadim07 pull request #4
Opened 2022-11-13 21:18 UTC by tsyk007

2022-11-13 21:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-14 09:25 UTC, GSemikozov requested changes

2022-11-14 09:25 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 0;
тут надо бы задать как в макете

2022-11-14 09:25 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину лучше жестко не фиксировать, пусть зависит от вложенного контента

2022-11-14 09:25 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
лучше добавить pointer-events: none

2022-11-14 09:52 UTC, GSemikozov approved these changes

2022-11-14 09:52 UTC, merged